refactor: sprint 9
Edmecom/java-filmorate pull request #1
Opened 2022-10-17 02:01 UTC by Edmecom

2022-10-17 19:36 UTC, andrew-larkin requested changes
Привет! Отличная реализация, за testRestTemplate отдельный плюс. Немного отрефакторить и проверить тесты - я добавил комментарии по коду, посмотри, пожалуйста

2022-10-17 19:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(++generatedId);
устанавливать id лучше после валидации

2022-10-17 19:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user.setId(++generatedId);
устанавливать id лучше после валидации

2022-10-17 19:36 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
по-хорошему, id никогда не должен быть null, потому что именно он будет потом вставлять в БД в качестве первичного ключа

2022-10-17 19:36 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = new Film(
чтобы не создавать новый фильм в каждом тесте, предлагаю просто вынести его создание в отдельный приватный метод, где будет создаваться "правильный" фильм. Затем мы вызываем этот метод в тесте, с помощью сеттера устанавливаем "неправильное" значение в нужное нам поле и тестим валидацию. Это немного сократит общий объем кода. А за testRestTemplate отдельный плюс!

2022-10-17 19:36 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
странная история с тестами - из 9 у меня отработал только один. Причина везде в том, что возвращается 400-й код вместо 500-го.

2022-10-18 19:51 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(++generatedId);
сделал

2022-10-18 19:52 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        user.setId(++generatedId);
сделал

2022-10-18 20:00 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private int id;
убрал @Null

2022-10-19 14:08 UTC, Edmecom commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +        Film film = new Film(
Сделал

2022-10-19 14:28 UTC, merged

2022-10-19 14:54 UTC, Edmecom commented on src/test/java/ru/yandex/practicum/filmorate/controller/UserControllerTest.java
> +class UserControllerTest {
Как я понял, именно благодаря тому что я добавил аннотаций в некоторых случаях возвращается 400 вместо 500.