refactor: sprint 10 v3
Edmecom/java-filmorate pull request #3
Opened 2022-11-05 10:50 UTC by Edmecom

Убрал из котроллеров всю бизнес-логику в сервисы.

2022-11-05 17:53 UTC, andrew-larkin requested changes
Привет! Небольшой рефакторинг требуется и дописать положительный сценарий для тестов.

2022-11-05 17:53 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      @ResponseBody
@ResponseBody можно не добавлять, если используются аннотации @...Mapping

2022-11-05 17:53 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getAll() {
давай все методы контроллера будем заворачивать в ResponseEntity, так мы добьемся единообразия. В методах, где возвращается void, можно так и указать ResponseEntity<Void>

2022-11-05 17:53 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmControllerAdvise.java
нам будет достаточно одного ConrollerAdvice, если посмотреть, то методы у них одинаковые, так что можно смело оставлять один и назвать его ErrorHandler или ExceptionHandler

2022-11-05 17:53 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
все правки в FilmController актуальны и тут

2022-11-05 17:53 UTC, andrew-larkin commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .andExpect(MockMvcResultMatchers.status().is4xxClientError());
нам нужен тест как на положительный, так и на отрицательный сценарий. Это актуально также для тестов для UserControllerTest

2022-11-06 10:40 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      @ResponseBody
сделал

2022-11-06 10:51 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmControllerAdvise.java
сделал

2022-11-06 11:53 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>      public List<Film> getAll() {
Сделал

2022-11-06 11:54 UTC, Edmecom commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
>  public class UserController {
Сделал

2022-11-06 12:39 UTC, Edmecom commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +                .andExpect(MockMvcResultMatchers.status().is4xxClientError());
Сделал

2022-11-06 12:39 UTC, closed without merging